version: '3'
services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - promnet

  grafana:
    image: grafana/grafana
    ports:
      - "9980:3000"
    networks:
      - promnet
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    networks:
      - promnet
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  promnet:

volumes:
  grafana_data: